Traceback (most recent call last):
  File "/opt/conda/envs/idm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/idm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/oracle/Research-Papers-Implementation/SRGAN/train/srresnet.py", line 63, in <module>
    train(model, train_loader, optimizer, criterion, num_epochs)
  File "/home/ubuntu/oracle/Research-Papers-Implementation/SRGAN/train/srresnet.py", line 47, in train
    for i,(lr_images,hr_images) in enumerate(train_loader):
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/oracle/Research-Papers-Implementation/SRGAN/dataset/srresnet.py", line 30, in __getitem__
    lr_image = self.transform_lr(transforms.toPILImage()(hr_image))
AttributeError: module 'torchvision.transforms' has no attribute 'toPILImage'. Did you mean: 'ToPILImage'?

Traceback (most recent call last):
  File "/opt/conda/envs/idm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/idm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/oracle/Research-Papers-Implementation/SRGAN/train/srresnet.py", line 63, in <module>
    train(model, train_loader, optimizer, criterion, num_epochs)
  File "/home/ubuntu/oracle/Research-Papers-Implementation/SRGAN/train/srresnet.py", line 47, in train
    for i,(lr_images,hr_images) in enumerate(train_loader):
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/oracle/Research-Papers-Implementation/SRGAN/dataset/srresnet.py", line 30, in __getitem__
    lr_image = self.transform_lr(transforms.toPILImage()(hr_image))
AttributeError: module 'torchvision.transforms' has no attribute 'toPILImage'. Did you mean: 'ToPILImage'?
